version: "3.3"

services:
  openvpn-monitor:
    image: ruimarinho/openvpn-monitor
    ports:
      - 8040:80
    environment:
      OPENVPNMONITOR_DEFAULT_DATETIMEFORMAT: "%d/%m/%Y %H:%M:%S"
      OPENVPNMONITOR_DEFAULT_LATITUDE: 52
      OPENVPNMONITOR_DEFAULT_LOGO: "logo.jpg"
      OPENVPNMONITOR_DEFAULT_LONGITUDE: 19
      OPENVPNMONITOR_DEFAULT_MAPS: True
      OPENVPNMONITOR_DEFAULT_SITE: "yuzukiko.net"
      OPENVPNMONITOR_SITES_0_ALIAS: "UDP"
      OPENVPNMONITOR_SITES_0_HOST: "192.168.1.10"
      OPENVPNMONITOR_SITES_0_NAME: "UDP"
      OPENVPNMONITOR_SITES_0_PORT: 5555
      OPENVPNMONITOR_SITES_0_SHOWDISCONNECT: True
      OPENVPNMONITOR_SITES_1_ALIAS: "TCP"
      OPENVPNMONITOR_SITES_1_HOST: "192.168.1.10"
      OPENVPNMONITOR_SITES_1_NAME: "TCP"
      OPENVPNMONITOR_SITES_1_PORT: 5555
    restart: unless-stopped
