version: "3"

services:
  youtrack:
    container_name: youtrack
    image:  jetbrains/youtrack:2021.4.32527
    ports:
      - 8000:8080
    volumes:
      - './youtrack-data/:/opt/youtrack/data'
      - './youtrack-conf/:/opt/youtrack/conf'
      - './youtrack-logs/:/opt/youtrack/logs'
      - './youtrack-backups/:/opt/youtrack/backups'
    restart: unless-stopped
volumes:
  youtrack-data:
  youtrack-conf:
  youtrack-logs:
  youtrack-backups: